#!/usr/bin/env bash
# mihomo-full 一键安装（需已安装 v2ray-agent）
set -euo pipefail
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info(){ echo -e "${GREEN}[+]${NC} $1"; }; warn(){ echo -e "${YELLOW}[!]${NC} $1"; }; err(){ echo -e "${RED}[✗]${NC} $1"; exit 1; }; title(){ echo -e "\n${CYAN}==== $1 ====${NC}\n"; }
INSTALL_DIR="/opt/mihomo-full"; OUTPUT_DIR="${INSTALL_DIR}/output"; FULL_PATH="/assets/static/a7f3c21e9b"; NODES_PATH="/assets/static/e9b2f1a7c3"
clear; echo -e "${CYAN}"; echo "  Mihomo 完整配置 + v2ray-agent 一键部署"; echo "  --------------------------------------"; echo "  · 客户端只导入一个固定订阅"; echo "  · 订阅地址不带 .yaml"; echo "  · 一键更新仅刷新落地节点"; echo -e "${NC}"
[[ $EUID -eq 0 ]] || err "请使用 root 运行：sudo bash install.sh"
title "1. 填写必要信息"
read -rp "请输入机场订阅链接: " AIRPORT_SUB_URL
[[ "$AIRPORT_SUB_URL" =~ ^https://[^[:space:]\"]+$ ]] || err "机场订阅必须使用 HTTPS，且不能含空格或双引号"
read -rp "请输入域名（已解析到本机 VPS，不要 https://，例 example.com）: " DOMAIN
DOMAIN="${DOMAIN#https://}"; DOMAIN="${DOMAIN#http://}"; DOMAIN="${DOMAIN%%/*}"
[[ "$DOMAIN" =~ ^[A-Za-z0-9.-]+(:[0-9]+)?$ ]] || err "域名格式不正确"
read -rp "v2ray-agent clashMeta 目录 [默认 /etc/v2ray-agent/subscribe_local/clashMeta]: " V2RAY_DIR
V2RAY_DIR="${V2RAY_DIR:-/etc/v2ray-agent/subscribe_local/clashMeta}"
echo; info "机场订阅 : $AIRPORT_SUB_URL"; info "域名     : $DOMAIN"; info "节点目录 : $V2RAY_DIR"; echo
read -rp "确认无误？(Y/n): " CONFIRM; [[ "${CONFIRM:-Y}" =~ ^[Yy]$ ]] || { echo "已取消"; exit 0; }
title "2. 写入文件"
mkdir -p "$INSTALL_DIR" "$OUTPUT_DIR"
{ printf "%s\n" "# auto-generated by install.sh"; printf "AIRPORT_SUB_URL=%q\n" "$AIRPORT_SUB_URL"; printf "FIXED_FULL_CONFIG_PATH=%q\n" "$FULL_PATH"; printf "FIXED_EXIT_NODES_PATH=%q\n" "$NODES_PATH"; printf "DOMAIN=%q\n" "$DOMAIN"; printf "V2RAY_AGENT_CLASHMETA_DIR=%q\n" "$V2RAY_DIR"; printf "OUTPUT_DIR=%q\n" "$OUTPUT_DIR"; } > "${INSTALL_DIR}/settings.conf"
chmod 600 "${INSTALL_DIR}/settings.conf"

# 核心文件均固定到已审核版本，避免安装时随 main 漂移
curl --fail --silent --show-error --location --proto "=https" --tlsv1.2 -o "${INSTALL_DIR}/generate.sh" "https://raw.githubusercontent.com/dukangalex/mihomo-full/9cbe69f193fef69a5b5509fa6830a34dede8cc83/generate.sh" || err "无法下载已审核 generate.sh"
curl --fail --silent --show-error --location --proto "=https" --tlsv1.2 -o "${INSTALL_DIR}/template.yaml" "https://raw.githubusercontent.com/dukangalex/mihomo-full/aeba5f3e052ec22c8e92e91b9c6808b8d9099b94/template.yaml" || err "无法下载 template.yaml"
curl --fail --silent --show-error --location --proto "=https" --tlsv1.2 -o "${INSTALL_DIR}/manage.sh" "https://raw.githubusercontent.com/dukangalex/mihomo-full/69c1a38fe63530dcf38fdfa5ab2d861fb44ab556/manage.sh" || err "无法下载 manage.sh"
chmod 700 "${INSTALL_DIR}/manage.sh"; chmod 700 "${INSTALL_DIR}/generate.sh"
ln -sf "${INSTALL_DIR}/manage.sh" /usr/local/bin/mihomo-full
if [[ ! -f "${INSTALL_DIR}/rulesets.local.conf" ]]; then printf '%s\n' '# provider|https_mrs_url|behavior|target|enabled' > "${INSTALL_DIR}/rulesets.local.conf"; fi
chmod 600 "${INSTALL_DIR}/rulesets.local.conf"
title "3. 生成配置"
bash "${INSTALL_DIR}/generate.sh"
title "4. Nginx 配置（必须）"
cat <<EOF
请把以下内容加入你的 Nginx server 块，然后执行 nginx -t && systemctl reload nginx：

location = ${FULL_PATH} {
    alias ${OUTPUT_DIR}/full-config.yaml;
    default_type application/octet-stream;
    add_header Cache-Control "no-cache";
}

location = ${NODES_PATH} {
    alias ${OUTPUT_DIR}/exit-nodes.yaml;
    default_type application/octet-stream;
    add_header Cache-Control "no-cache";
}

location /assets/static/ { return 404; }
EOF
if command -v nginx >/dev/null 2>&1; then info "检测到 Nginx 已安装"; else warn "未检测到 Nginx，请自行配置 Web 服务器"; fi
title "完成"
echo -e "客户端导入：${GREEN}https://${DOMAIN}${FULL_PATH}${NC}"; echo "更新落地：${INSTALL_DIR}/generate.sh"; echo "管理入口：mihomo-full"; info "全部完成"
