#!/usr/bin/env bash
# mihomo-full 一键安装（需已安装 v2ray-agent）
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${GREEN}[+]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
err()   { echo -e "${RED}[✗]${NC} $1"; exit 1; }
title() { echo -e "\n${CYAN}==== $1 ====${NC}\n"; }

INSTALL_DIR="/opt/mihomo-full"
OUTPUT_DIR="${INSTALL_DIR}/output"
FULL_PATH="/assets/static/a7f3c21e9b"
NODES_PATH="/assets/static/e9b2f1a7c3"

clear
echo -e "${CYAN}"
echo "  Mihomo 完整配置 + v2ray-agent 一键部署"
echo "  --------------------------------------"
echo "  · 客户端只导入一个固定订阅"
echo "  · 订阅地址不带 .yaml，不易识别"
echo "  · 一键更新仅刷新落地节点"
echo -e "${NC}"

[[ $EUID -eq 0 ]] || err "请使用 root 运行：sudo bash install.sh"

title "1. 填写必要信息"

read -rp "请输入机场订阅链接: " AIRPORT_SUB_URL
[[ -n "$AIRPORT_SUB_URL" ]] || err "机场订阅不能为空"

read -rp "请输入域名（已解析到本机 VPS，不要 https://，例 example.com）: " DOMAIN
DOMAIN="${DOMAIN#https://}"
DOMAIN="${DOMAIN#http://}"
DOMAIN="${DOMAIN%%/*}"
[[ -n "$DOMAIN" ]] || err "域名不能为空"

read -rp "v2ray-agent clashMeta 目录 [默认 /etc/v2ray-agent/subscribe_local/clashMeta]: " V2RAY_DIR
V2RAY_DIR="${V2RAY_DIR:-/etc/v2ray-agent/subscribe_local/clashMeta}"

echo
info "机场订阅 : $AIRPORT_SUB_URL"
info "域名     : $DOMAIN"
info "节点目录 : $V2RAY_DIR"
echo
read -rp "确认无误？(Y/n): " CONFIRM
[[ "${CONFIRM:-Y}" =~ ^[Yy]$ ]] || { echo "已取消"; exit 0; }

title "2. 写入文件"

mkdir -p "$INSTALL_DIR" "$OUTPUT_DIR"

cat > "${INSTALL_DIR}/settings.conf" <<EOF
# auto-generated by install.sh
AIRPORT_SUB_URL="${AIRPORT_SUB_URL}"
FIXED_FULL_CONFIG_PATH="${FULL_PATH}"
FIXED_EXIT_NODES_PATH="${NODES_PATH}"
DOMAIN="${DOMAIN}"
V2RAY_AGENT_CLASHMETA_DIR="${V2RAY_DIR}"
OUTPUT_DIR="${OUTPUT_DIR}"
EOF

# 写入精简版 generate.sh（与仓库 generate.sh 逻辑一致）
curl --fail --silent --show-error --location --proto "=https" --tlsv1.2 -o "${INSTALL_DIR}/generate.sh" \
  "https://raw.githubusercontent.com/dukangalex/mihomo-full/e8133d667e29f06f3421b4e7a0775491cc2a3718/generate.sh" || true
if [[ ! -s "${INSTALL_DIR}/generate.sh" ]]; then
  warn "无法下载 generate.sh，请手动复制仓库中的 generate.sh"
else
  chmod +x "${INSTALL_DIR}/generate.sh"
fi

if [[ ! -f "${INSTALL_DIR}/template.yaml" ]]; then
  info "下载 template.yaml..."
  curl --fail --silent --show-error --location --proto "=https" --tlsv1.2 -o "${INSTALL_DIR}/template.yaml" \
    "https://raw.githubusercontent.com/dukangalex/mihomo-full/e8133d667e29f06f3421b4e7a0775491cc2a3718/template.yaml" || \
    warn "请手动把 template.yaml 放到 ${INSTALL_DIR}/"
fi

info "文件已写入 ${INSTALL_DIR}"

# 安装小白管理入口
curl --fail --silent --show-error --location --proto "=https" --tlsv1.2 -o "$INSTALL_DIR/manage.sh" "https://raw.githubusercontent.com/dukangalex/mihomo-full/18288d4dbdd024f44e776444dbce4b682043bc93/manage.sh" || warn "无法下载 manage.sh"
chmod 700 "$INSTALL_DIR/manage.sh" 2>/dev/null || true
ln -sf "$INSTALL_DIR/manage.sh" /usr/local/bin/mihomo-full
if [[ ! -f "$INSTALL_DIR/rulesets.local.conf" ]]; then printf '%s
' '# provider|https_mrs_url|behavior|target|enabled' > "$INSTALL_DIR/rulesets.local.conf"; fi
chmod 600 "$INSTALL_DIR/rulesets.local.conf"

title "3. 生成配置"
if [[ -f "${INSTALL_DIR}/template.yaml" && -x "${INSTALL_DIR}/generate.sh" ]]; then
  bash "${INSTALL_DIR}/generate.sh"
else
  warn "缺少 template.yaml 或 generate.sh，跳过生成"
fi

title "4. Nginx 配置（必须）"

cat <<EOF
请把以下内容加入你的 Nginx server 块，然后执行 nginx -t && systemctl reload nginx：

location = ${FULL_PATH} {
    alias ${OUTPUT_DIR}/full-config.yaml;
    default_type application/octet-stream;
    add_header Cache-Control "no-cache";
}

location = ${NODES_PATH} {
    alias ${OUTPUT_DIR}/exit-nodes.yaml;
    default_type application/octet-stream;
    add_header Cache-Control "no-cache";
}

location /assets/static/ {
    return 404;
}

EOF

if command -v nginx >/dev/null 2>&1; then
  info "检测到 Nginx 已安装"
  echo "配置改好后执行：nginx -t && systemctl reload nginx"
else
  warn "未检测到 Nginx，请自行配置 Web 服务器"
fi

title "完成"
echo -e "客户端导入：${GREEN}https://${DOMAIN}${FULL_PATH}${NC}"
echo "更新落地：${INSTALL_DIR}/generate.sh"
echo "改机场：  nano ${INSTALL_DIR}/settings.conf && ${INSTALL_DIR}/generate.sh"
info "全部完成"
